sonar.organization=som-energia
sonar.projectKey=Som-Energia_som_sync_openerp_modules
sonar.language=py

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=som_sync_openerp
sonar.inclusions=**/*.py

# Exclude test files from main source analysis
sonar.exclusions=**/tests/**
sonar.test.inclusions=som_sync_openerp/tests/**

# Coverage report paths
sonar.python.coverage.reportPaths=coverage-xml

# Definim un identificador per a l'exclusió (p. ex. "p1")
sonar.issue.ignore.multicriteria=p1
# Indiquem quina regla és (S1192 és la de literals repetits)
sonar.issue.ignore.multicriteria.p1.ruleKey=python:S1192
# Indiquem a quins fitxers s'aplica (* vol dir a tots)
sonar.issue.ignore.multicriteria.p1.resourceKey=**/*.py
