#  -*- coding: utf-8 -*-
from __future__ import absolute_import
from . import odoo_sync
from . import odoo_sync_model_config
from . import account_account
from . import account_invoice
from . import account_invoice_line
from . import account_journal
from . import account_move
from . import account_move_line
from . import payment_line
from . import payment_mode
from . import payment_order
from . import norma57_file
from . import res_country
from . import res_country_state
from . import res_municipi
from . import res_partner_bank
from . import res_partner
from . import res_partner_address
from . import giscedata_facturacio_devolucio
from . import account_invoice_fraccionament
