# This workflow will pass tests of module passed by input

name: som_sync_openerp
on:
  workflow_dispatch:
  pull_request: # PR

jobs:
  erp-tests-module:
    uses: Som-Energia/openerp_som_addons/.github/workflows/reusable_workflow.yml@main
    with:
      module: som_sync_openerp
      pyversion: '["2.7"]'
      upload_coverage: true
    secrets:
      ACCESS_TOKEN_GA: ${{ secrets.ACCESS_TOKEN_GA }}
      ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
      SRID: ${{ secrets.SRID }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-22.04
    needs: erp-tests-module       # <-- Depèn del job que crida el reusable workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage.xml from tests
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@9598b8a83feef37de07f549027fab50ecffe6a6e
        with:
          organization: som-energia
          projectKey: Som-Energia_som_sync_openerp_modules
          projectName: som_sync_openerp_modules
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
